// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imidll/selfshop/pkg/logger (interfaces: SafeSyncer)
//
// Generated by this command:
//
//	mockgen -destination=mocks/syncer.go -package=loggermocks . SafeSyncer
//

// Package loggermocks is a generated GoMock package.
package loggermocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSafeSyncer is a mock of SafeSyncer interface.
type MockSafeSyncer struct {
	ctrl     *gomock.Controller
	recorder *MockSafeSyncerMockRecorder
	isgomock struct{}
}

// MockSafeSyncerMockRecorder is the mock recorder for MockSafeSyncer.
type MockSafeSyncerMockRecorder struct {
	mock *MockSafeSyncer
}

// NewMockSafeSyncer creates a new mock instance.
func NewMockSafeSyncer(ctrl *gomock.Controller) *MockSafeSyncer {
	mock := &MockSafeSyncer{ctrl: ctrl}
	mock.recorder = &MockSafeSyncerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSafeSyncer) EXPECT() *MockSafeSyncerMockRecorder {
	return m.recorder
}

// Sync mocks base method.
func (m *MockSafeSyncer) Sync() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync")
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MockSafeSyncerMockRecorder) Sync() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockSafeSyncer)(nil).Sync))
}
